#!/bin/bash

#SBATCH --job-name="ram-prs"
#SBATCH --mail-type=NONE         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=ritalighosh@iisc.ac.in    # Where to send mail.  Set this to your email address
#SBATCH -p debug
#SBATCH -t 2-48:00:00  #dd-hh:mm:ss
#SBATCH -n 168
#SBATCH --output=%x-%j.log

echo "Working Directory = $(pwd)"

cd $SLURM_SUBMIT_DIR
export PROG="./pluto -catalyst 10 temperature-pipeline.py density-pipeline.py cgm-tracer-pipeline.py disk-tracer-pipeline.py wind-tracer-pipeline.py mach-pipeline.py pbykB-pipeline.py vx-pipeline.py vy-pipeline.py vz-pipeline.py"

module load catalyst/v2
module load hdf5/parallel

mkdir -p output/Log_Files

srun $PROG
